README.md: guessinggame.sh
	@echo "# Guessing Game" > README.md
	@echo >> README.md
	@echo "Date and Time at which make was run:" >> README.md
	@date '+%Y-%m-%d %H:%M:%S' >> README.md
	@echo >> README.md
	@echo "Number of lines of code in guessinggame.sh:" >> README.md
	@wc -l guessinggame.sh | awk '{print $$1}' >> README.md

.PHONY: clean

clean:
	@rm -f README.md
